services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
    ports:
      - "5432:5432"
    volumes:
      - forum_db:/var/lib/postgresql/data
    networks:
      - forum-net

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - forum-net

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  forum-api:
    container_name: forum-api
    image: alancs7/simple-forum-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/forum
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EMAIL_HOSTNAME: mail-dev
      EMAIL_USERNAME: username
      EMAIL_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - forum-net
    depends_on:
      - postgres
      - redis

volumes:
  forum_db:
  redis-data:

networks:
  forum-net:
    driver: bridge