services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
    ports:
      - "5432:5432"
    volumes:
      - forum_db:/var/lib/postgresql/data
    networks:
      - forum-net

  forum-api:
    container_name: forum-api
    image: alancs7/simple-forum-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/forum
    ports:
      - "8080:8080"
    networks:
      - forum-net
    depends_on:
      - postgres

volumes:
  forum_db:

networks:
  forum-net:
    driver: bridge