spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: username
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect