spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/forum}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret-key: T1r@mpOnEtk#8xIS9evcLy^DAqE$CnMlFgWhiopRTuKBsNjXg4z7V0QdM53aYw6U

cache:
  ttl: 60 # minutos